version: '3'

services:
  snapserver:
    build:
      context: .
    container_name: snapserver
    image: audiostation/snapcast:v1.0
    volumes:
      - /tmp/sharesound:/tmp/sharesound
    command: "snapserver -s pipe:///tmp/sharesound/snapfifo?name=Radio"
    ports:
      - "1704:1704"
      - "1705:1705"
